mevdschee/php-crud-api

- api.php
I would expect a 403 header if authentication fails
Exit the program with a 403 is an invalid exit status.
According to http://php.net/manual/en/function.exit.php exit statuses should be in the range 0 to 254.
Because exit does not throw a header, you can not redirect users to a login page, when trying to call the api.php script
> Exit statuses should be in the range 0 to 254

- api.php
- tests/tests.php
Feel free to change the behavior if this is undesired. This adds the exclude= parameter. I added a few tests to demonstrate the behavior. If both include and exclude are present, then include is run first pulling in any relations and then exclude is run. If there are multiple tables in the return, the exclude parameter must be in the format {table}.{column/field}. If there is a single table in the return, the exclude parameter may just be {column/field}. This could be improved to exclude entire tables, say {table}.*?. Some exclusions have unintended behavior. For example, if you change the test from &exclude=comments.message to &exclude=category.id, it will drop all the fields from category instead of just removing category.id. Otherwise, it works for general cases. (This includes a test …
> 1st attempt at adding exclude= (issue #136) try#2

- api.php
First of all, thanks for building this great php api framework and sharing it with the world!
I am a SAP Developer mainly developping JS apps in [SAPUI5 / OpenUI5](https://open.sap.com/)
In order to make SAPUI5 work with your API, I have made a [SAPui5 model implementation](https://github.com/VyseExhale/OpenUI5-SAPUI5-CRUDModel) of your api
With this model I can retrieve, edit and send data to your api and bind it to my views.
Other SAPui5 Models (like Odata) auto convert api response data to usable js json objects.
for example. Any date/time fields in the api will in js be converted to a new Date() object.
I wanted to do this too with my model implementation of your api.. 
In order to do that, I needed to know what db column and types my db tables have.
I found that in your metadata …
> Database column type in metadata

- api.php
@VyseExhale : This is similar to your pull request.  There are other places to add the x-dbtype.  The reflect_type entry translates the MySQL numeric types to actual types.  For now, the other db's will have to tweak the code to provide the full type translation (IE: SqlServer will show numbers for x-dbtype).   Since we are just including an x-dbtype, this does not really impact the swagger 2.0 standard at the moment.    I tested this against the MySQL test database and resultant json at swagger.io.   It is fine.   The unit tests for sqlite, postgresql and mysql pass.
It is a step in the right direction I think.  Note the icon is really a binary data blob instead of a string.   In actuality, I believe you deliver it as a string translated to hex?
>                 icon:
> …
> Adding "x-dbtype" to show database field type

- api.php
This addresses my first report in #190. I ran the test suite, and things are still working fine with Postgres.
I stopped short of implementing the XML field type in Postgres as I think that will be a significant enough change to warrant its own PR.
I did not add another test for this as it's a pretty minimal semantic change, but I can do so if you think it's necessary.
Thanks for you consideration!
> Allowing json, jsonb in postgres

- api.php
- tests/tests.php
Fix for schema object.  If no fields are required, do not add required tag. 
Depending on the database you were testing, you might have ended up with valid schema.  In issue #193, this bug is triggered when a table has no required fields.  
The required parameter in the schema: section would result in:
`required: []`
which is invalid for the swagger editor.   The code update checks for at least one or more fields that are required before printing out an array.
I looked for an explanation in the swagger specification (twice) and could not find it.  Ok.  It is part of the JSON Schema Validation specification (https://tools.ietf.org/html/draft-fge-json-schema-validation-00)
```
5.4.3.  required
5.4.3.1.  Valid values
The value of this keyword MUST be an array.  This array MUST have at
least …
```
> A little bugfix.

- api.php
Hi there,
We're allmost there, I found 2 bugs, one I solved with this pull request:
The first one: on deleting multiple rows at once and applying my soft delete [see example 209](https://github.com/mevdschee/php-crud-api/issues/209) I got an 404 errror : Subject caused by the [updateObject method](https://github.com/mevdschee/php-crud-api/blob/master/api.php#L1533-L1535) 
The other you will find here [209](https://github.com/mevdschee/php-crud-api/issues/209), this needs to be discussed first.
> Bug in beforehandler, on deleting multiple rows

- api.php
Currently the swagger description is no longer outputted by requesting the url `http://example.com/api.php`. This behavior affects for example the project `php-crud-ui`.
This commit is a fix, that the swagger description is outputted the when scriptfile api.php is requested without any given entity/subject. 
I've decided not to implement that change in the constructor `__construct()` where the request param is filled. Maybe later you want to access the full unmodified request/path info string and therefore I've extended the method `executeCommand()`.
In my current development environment I have no possiblity to extend and run your phpunit test cases. This can be a task for the future to compare the output of a request of the api.php root (/) for containing some swagger information.
> Swagger: Output swagger description

- api.php
Following our conversation [210](https://github.com/mevdschee/php-crud-api/pull/210) there are now 3 issues doing a soft delete :
The first issue is in the "applyBeforeHandler":
```php
$callback($action,$database,$table,$id,$inputs[$i]);
```
$id shoud be $ids[$i], you've probably missed that one :
```php
$callback($action,$database,$table,$ids[$i],$inputs[$i]);
```
The second issue will rise if you do 2 or more (soft)deletes: Like
```php
DELETE http://localhost/api.php/categories/1,2
```
In the second [loop](https://github.com/mevdschee/php-crud-api/blob/master/api.php#L1140-L1144) of the applyBeforeHandler, the $action is overwritten by the first loop.. so the in the second before call, the $cmd = 'update'.. so the 2nd one wil never be deleted
first:
```php
'before'=>function(&$cmd, $db, …
```
> Bugfix multiple soft deletes (beforeHandler)

- .gitignore
- tests/blog_postgresql.sql
- tests/blog_sqlite.sql
As I was setting up for #194 I realized that the SQLite and Postgres databases didn't have the same fields. I also made sure to enable the Postgres GIS extension (if it wasn't already).
I've now got the tests running in SQLite, MySQL, and Postgres, so now the real work can start :-)
> Updating seeds for tests

- .travis.yml
- README.md
- composer.json
- tests/config.php.travis
- travisphp.ini
Addresses #226 
This adds configuration to let Travis automatically run our tests every time we make updates. Whoo!
I currently have it set up to run on my fork of this repo: https://travis-ci.org/karllhughes/php-crud-api
You will need to create an account on Travis and add the main repository. Once added, you should be able to set it to auto-run tests when PRs are made.
There are some known deficiencies in this PR. I'm going to open an issue to deal with them later. I figured it would be better to have half our tests automatically running than to have none of them!
> Adding travis configuration

- .travis.yml
To address this comment: https://github.com/mevdschee/php-crud-api/issues/238#issuecomment-294307121
Apparently Travis already installs MySQL and Postgres is in the add-ons section, so these two lines were unnecessary. They were causing that warning message in Travis.
More to come on improving the Travis later.
> Removing DBs as services

- api.php
- tests/Tests.php
Issue:
When sending JSON in the body of a POST
request from an HTML form - for creating
a new record, a new record was being created,
but with null as the value for all the fields,
instead of the values supplied.
Cause:
The template text in the textarea field, in the
HTML form had some leading whitespace. On looking
through the source, json_decode is being called
only if the first character of the $data variable
is a '{' or a '['.
JSON Specification RFC4627
https://tools.ietf.org/html/rfc4627#section-2
says that insignificant
whitespace is allowed before or after any of the
six structural characters - '{','[',']','}',':',','
where whitespace is defined as:
ws = *(
%x20 /              ; Space
%x09 /              ; Horizontal tab
%x0A /              ; Line feed or New line
%x0D …
> Handle leading whitespace in JSON body

- api.php
- tests/Api.php
- tests/Tests.php
Symptom:
----------
Trying to create an object sending a seemingly correct JSON request in a
POST message - was giving a 404 not found error.  When looking at the cause
in the browser devtools - the body of the response contained "Not found (input)"
Cause:
-------
We were trying to validate parameters - even when the POST body
contained invalid JSON.  
We call json_decode($data) in retrieveInputs - but, do not check for errors.
The JSON request was malformed and it had omitted the double quotes.
example: { fieldName : "fieldValue" }
Expected behavior and fix:
---------------------------
A POST request with malformed JSON should get a 400 "bad request"
response. Even more helpful would be an error code indicating why the
JSON was bad.
If we call json_decode(), afterwards, [we immediately …
> Correct 400 response to malformed json in POST

- composer.json
- tests/TestBase.php
I use the `PHPUnit\Framework\TestCase` notation instead of `PHPUnit_Framework_TestCase` while extending our TestCase. This will help us migrate to PHPUnit 6, that [no longer support snake case class names](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#changed-1).
I just need to bump PHPUnit version to [`^4.8.35`](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-4.8.md#4835---2017-02-06), that support this namespace.
> Use PHPUnit\Framework\TestCase instead of PHPUnit_Framework_TestCase

- api.php
'utf8' in mySQL is actually a 3-byte encoding that cannot encode characters that occupy 4 bytes in UTF-8. 'utf8mb4' is a saner default.
> Use utf8mb4 instead of utf8 in commented-out starter code

- api.php
When some table's description has `control-characters`, likes
`\t` `\n`,
swagger that generated by `/api.php` is a defective json
> Escape control-characters in generated swagger

- README.md
The Vue file calls to `api.php/` with trailing slash, the given config returns a nginx-404 on that.
> Fix nginx config for api.php/ (with trailing slash)

- api.php
- src/Tqdev/PhpCrudApi/Middleware/Router/SimpleRouter.php
I made this fix because it was throwing an error 500: `$response` was not defined (line 130).
To trigger this error, I attempted to add a timestamp (ie. 1558688256) in a `DATETIME` column.
> Add a default error in SimpleRouter

- api.php
1. if the pkName is not "id" it differs from /components/parameters. So as a workaround I would hardcode it (otherwise openapi validators are not happy)
2. openapi specs require unique operationId field
> Fix for pkName and openapi specs

- README.md
- api.php
- src/Tqdev/PhpCrudApi/Middleware/AuthorizationMiddleware.php
Adds a new authorization middleware config option:
'authorization.allowOpenApiAccessHandler' => function () {
return false;
},
Returning false from this operation will disable the OpenAPI endpoint
Fixes #672
> Allow authorization handler to disable openapi

- README.md
- api.php
- src/Tqdev/PhpCrudApi/Api.php
- src/Tqdev/PhpCrudApi/Config.php
- src/Tqdev/PhpCrudApi/Middleware/Base/Middleware.php
- src/Tqdev/PhpCrudApi/Middleware/CatchErrorsMiddleware.php
- src/Tqdev/PhpCrudApi/Middleware/CorsMiddleware.php
- src/Tqdev/PhpCrudApi/Middleware/Router/SimpleRouter.php
Replaces error handling in API@handle with a middleware that will catch
throwables. If applied after cors middleware, CORS headers will be
enabled for error messages.
Fixes #645
> CORS headers not sent when an exception is thrown

- README.md
- api.php
- src/Tqdev/PhpCrudApi/Middleware/DbAuthMiddleware.php
- tests/functional/002_auth/003_db_auth.log
Adds a `/me` endpoint to the dbAuth middleware which returns the current user (if you're logged in).
> Add current user endpoint to db authentication

- src/Tqdev/PhpCrudApi/Middleware/XsrfMiddleware.php
As described here: https://github.com/mevdschee/php-crud-api/issues/776#issue-841088753, I couldn't get the XsrfMiddleware to work.
Debugging extensively, I found two issues:
1) My front-end (Angular / httpClient) wasn't able to detect the XSRF-TOKEN Cookie, because its "path" value was not "/". Because of that, it did not send the X-XSRF-TOKEN Header. Setting the Cookie "path" value to "/" via XsrfMiddleware/getToken solved this problem.
2) When sending X-XSRF-TOKEN:	9aead2ceb0e150e1 in the Header, $request->getHeader($headerName) returns an Array ( [0] => 9aead2ceb0e150e1 ) - at least in my test cases. So "$token != $request->getHeader($headerName)" was always false. Changing the condition to "$token != $request->getHeader($headerName)[0]" solved this problem.
Tested with Mozilla …
> XsrfMiddleware.php proposal

- src/Tqdev/PhpCrudApi/Middleware/JwtAuthMiddleware.php
In some cases, auth0 includes a second aud for userinfo endpoint.  Tokens can have multiple target audiences as long as the custom API’s signing algorithm is set to RS256.  Works with auth0 if machine-to-machine api userinfo is added as a second aud.  This patch prevents JWT validation from failing in that case.  See https://community.auth0.com/t/my-token-has-multiple-audiences-is-that-normal/41417
> fixes problem with multiple aud

- src/Tqdev/PhpCrudApi/Middleware/DbAuthMiddleware.php
If you try to change the password and `$pkName ` isn't contained inside `'dbAuth.returnedColumns'`, dbAuth won't know the column containing the id and will returns this error: 
<b>Warning</b>:  Undefined array key "id" in <b>C:\XAMPP\htdocs\api.php</b> on line <b>7978</b><br />
{"code":9999,"message":"Tqdev\\PhpCrudApi\\Database\\GenericDB::updateSingle(): Argument #3 ($id) must be of type string, null given, called in C:\\XAMPP\\htdocs\\api.php on line 7978"}
> [dbAuth] add pkName to Columnnames if not contained inside 'dbAuth.returnedColumns'

- src/Tqdev/PhpCrudApi/Middleware/DbAuthMiddleware.php
- src/Tqdev/PhpCrudApi/Record/ErrorCode.php
Prevent empty or only whitespace username on dbauth register endpoint. What's your thoughts about this?
> prevent empty username on dbauth register endpoint

- src/Tqdev/PhpCrudApi/Middleware/DbAuthMiddleware.php
Updated middleware to trim leading and/or trailing spaces in username. Before this, if a username is `jsmith`, `jsmith  ` or ` jsmith` will result to authentication failed due to extra spaces before or after the printable or visible characters in the username. Not sure if it is intentional, but it's confusing if these usernames will be treated as distinct. 😁
> Updated DbAuthMiddleware to trim leading and/or trailing spaces in username
