README.md

Trailing , in the filter caught me off guard, i figured i'd be nice to have an example of using the "is null" filter…

Added Example for is Null

---

.gitignore
README.md
api.php
config-template.php

Wanted to take a shot at implementing authentication. If you are interested I can comment some more of the code changes and write some unit tests if you like

Authentication

---

api.php

In response to issue [#182](https://github.com/mevdschee/php-crud-api/issues/182)

List + Filter NE added

---

api.php

Hi Maurits,
I needed a callback function that got triggered on a new db entry (Create).
For example I wanted to send an e-mail to a newly registered member.
In this example I have a "members" table with the columns: id , firstName, lastName, email
the yourEmailFunction method will send a welcome message to the newly entered member.
```php
$api = new PHP_CRUD_API(array(
/* 
......
all other settings 
*/
'after_create'=>function($db,$tab,$row) {
if ($tab == 'members') 
yourEmailFunction($row['firstName'],$row['lastName'],$row['email']);
}
}
));
$api->executeCommand();
```
Tell me you thoughts... maybe if you like it and willing to accept the pull request I could also create an after_delete and after_update method.

after_create

---

api.php

Possible fix for [issue 206](https://github.com/mevdschee/php-crud-api/issues/206)
soft delete example
```php
'before'=>function(&$cmd, &$db, &$tab, &$id, &$in) { 
if ($cmd == 'delete') {
$cmd = 'update'; // change command to update
foreach($in as $k => $o) {
$in[$k]->deleted = date('Y-m-d H:i:s', time());
}				
}
},
'column_authorizer'=>function($cmd, $db ,$tab, $col) { 
return ( ! in_array($col, array('deleted')));
},
'record_filter'=>function($cmd,$db,$tab) { 
return array('deleted,is,null');
}
```

Possible fix for issue 206

---

.gitignore
README.md
composer.json

This addresses #188.
Right now [the package](https://packagist.org/packages/mevdschee/php-crud-api) is reading my branch of the github repo, and it's not auto-updating yet. You can edit the composer package's repository here: https://packagist.org/packages/mevdschee/php-crud-api/edit?
Then you can add a [Github service hook](https://packagist.org/about#how-to-update-packages) to auto-update the package when you update this file.
I also added some very simple documentation.

Composer support

---

extras/core.php

Minor change. Love this Core project!

Updated the Delete command in the core.php file

---

api.php

Fixes the generated output of the API documentation to include an object for the database table.
This allows Swagger generated clients to function properly. ish.

Update api.php to fix API documentation

---

extras/core.php

Small omission that prevented mysqli_error from working properly

Add a parameter expected by mysqli_error()

---

api.php
tests/Tests.php

added many tests for tenancy + fix for PHP 7.2 warning regarding "Countable"

added tests for tenancy + fix for PHP 7.2

---

lib/php_crud_api_transform.py

Integrated a test in for __main__ which uses the example from the docs.

Transform algorithm in python 3

---

README.md

in seems to work with strings as well. Sorry for the 2 pull requests, still figuring out how this online github thing works....

Add test for filter in condition with strings

---

README.md

- Style more README file
- Add some links
- Fix typo

Style README

---

README.md
examples/clients/auth0/vanilla.html
examples/clients/firebase/vanilla-success.html
examples/clients/firebase/vanilla.html

Add Firebase JWT example + docs for Firebase & Auth0

---

README.md

Documentation update. Related discussion: https://github.com/mevdschee/php-crud-api/issues/606.

Update README.md: doc for firebase jwt

---

src/Tqdev/PhpCrudApi/Column/Reflection/ReflectedTable.php

Do not add null columns when getting foreign keys

---

src/Tqdev/PhpCrudApi/Middleware/DbAuthMiddleware.php

added configuration for usertable fields name

---

README.md
api.include.php
api.php
src/Tqdev/PhpCrudApi/Api.php
src/Tqdev/PhpCrudApi/Config.php
src/Tqdev/PhpCrudApi/Controller/JsonResponder.php
src/Tqdev/PhpCrudApi/Middleware/JsonMiddleware.php
src/Tqdev/PhpCrudApi/ResponseFactory.php

add 'jsonOptions' config

---

README.md
api.php

Add others init commands to execute on new connections.

 Add others init commands resolve #879 

---

README.md
src/Tqdev/PhpCrudApi/Middleware/DbAuthMiddleware.php

Allowing to auto-login after registration. I'm currently not able to run and write unit tests... but It's working as intended for me - and basically a simple code  (manual testing).
I was logged in (without logging out) and registered a new user. I expected to be singed in with this account after, but unfortunately it was still the first user - quite confusing.

Auto login
